library(shiny)
library(leaflet)
library(shinydashboard)
library(DT)
library(raster)
library(googleVis)
library(openintro)
library(data.table)

cat_choice_map <- c("Social Determinants", "Health Outcomes")
subcat_choice_map <- c("Economic Stability", "Neighborhood / Environment", "Education", "Food", "Community / Social", "Healthcare System")
metric_choice_map <- c("Unemployment", "Income Inequality")
detail_choice_map <- c("State", "County")

cat_choice_x <- c("Social Determinants", "Health Outcomes")
subcat_choice_x <- c("Economic Stability", "Neighborhood / Environment", "Education", "Food", "Community / Social", "Healthcare System")
metric_choice_x <- c("Unemployment", "Income Inequality")
cat_choice_y <- c("Social Determinants", "Health Outcomes")
subcat_choice_y <- c("General Health", "Disease Specific")
metric_choice_y <- c("Poor Physical Health Days per Month", "Poor Mental Health Days per Month", "Obesity Rate (%)", "Preventable Hospital Stays per 10,000 People", "Life Expectancy")

detail_choice_table <- c("State", "County")

USA_county <- getData("GADM", country="usa", level=2)
USA_state <- getData("GADM", country="usa", level=1)

# sdoh_df_metric_state <- na.omit(dbGetDataStates(conn, "state, unemployment"))
# sdoh_df_metric_state$state <- abbr2state(as.character(sdoh_df_metric_state$state))
# sdoh_df_metric_state <- na.omit(sdoh_df_metric_state)
# temp <- merge(USA_state, sdoh_df_metric_state, by.x="NAME_1", by.y="state", all.x=TRUE)
# mypal <- colorNumeric(palette="viridis", domain=temp[["unemployment"]], na.color="grey")
